# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 814364ff173c1d3f438fb838677687a9695ba7afc211986a4dba196f5e845ced41cc8494bc49c1921a48cec06f6b28f4fcbcd8d012f31103e1a05d71f86d7175

test:
  secret_key_base: cd21a5b8f994124bcf79d3df688df14c76eb29d74b3b8065b13ae4a0f0c86f0df2612c2ee2774eb89827fdbe6de3b02c664381ef5655fb980882e1a168f141e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
